export var API_URL = "http://192.168.1.71:3000";

export var API = {
  login: "/api/mobile/auth/login",
  register: "/api/mobile/auth/register",
  profile: "/api/mobile/auth/profile",
  refresh: "/api/mobile/auth/refresh",
  me: "/api/mobile/me",
  artworks: "/api/artworks",
  myArtworks: "/api/mobile/me/artworks",
  artworkLike: (id) => `/api/artworks/${id}/like`,
  users: "/api/users",
  userProfile: (u) => `/api/users/${u}`,
  userFollow: (id) => `/api/mobile/users/${id}/follow`,
  posts: "/api/mobile/posts",
  postLike: (id) => `/api/mobile/posts/${id}/like`,
  postComment: (id) => `/api/mobile/posts/${id}/comment`,
  exhibitions: "/api/exhibitions",
  events: "/api/events",
  orders: "/api/orders",
  commissions: "/api/commissions",
  conversations: "/api/messages/conversations",
  messages: "/api/messages",
  music: "/api/music",
  notifications: "/api/notifications",
  upload: "/api/upload",
  search: "/api/search",
};
