import{useState,useEffect}from"react";import{View,Text,FlatList,TouchableOpacity as T,Image,ActivityIndicator,Dimensions}from"react-native";import{users,artworks as artSvc}from"../../services/data";import{colors as c,fs,fw,sp,rad}from"../../constants/theme";
var W=Dimensions.get("window").width,G=8,CW=(W-sp.lg*2-G)/2;
export default function ArtistProfile({route,navigation:n}){var{username}=route.params;var[p,sP]=useState(null);var[arts,sA]=useState([]);var[ld,sL]=useState(true);var[fol,sF]=useState(false);
useEffect(()=>{(async()=>{try{var d=await users.get(username);sP(d);if(d._id){var a=await artSvc.list({artistId:d._id,status:"all",limit:50});sA(a.artworks||[])}}catch{}sL(false)})()},[username]);
if(ld)return<View style={{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:c.bg}}><ActivityIndicator color={c.teal}/></View>;
if(!p)return<View style={{flex:1,backgroundColor:c.bg}}><Text style={{color:c.textMuted,textAlign:"center",marginTop:60}}>Not found</Text></View>;
return<FlatList style={{flex:1,backgroundColor:c.bg}} data={arts} keyExtractor={i=>i._id} numColumns={2} contentContainerStyle={{paddingHorizontal:sp.lg,paddingBottom:100}} ListHeaderComponent={<View style={{alignItems:"center",paddingVertical:sp.lg,marginBottom:sp.md}}>{p.avatar?<Image source={{uri:p.avatar}} style={{width:80,height:80,borderRadius:40,marginBottom:sp.md,borderWidth:2,borderColor:c.borderLight}}/>:<View style={{width:80,height:80,borderRadius:40,marginBottom:sp.md,backgroundColor:c.surfaceDim,borderWidth:2,borderColor:c.borderLight}}/>}<Text style={{fontSize:fs.xxl,fontWeight:fw.light,color:c.text}}>{p.displayName}</Text>{p.location&&<Text style={{fontSize:fs.sm,color:c.textMuted,marginTop:sp.xs}}>📍 {p.location}</Text>}{p.bio&&<Text style={{fontSize:fs.sm,color:c.textSecondary,textAlign:"center",marginTop:sp.md,lineHeight:20,maxWidth:280}}>{p.bio}</Text>}
<View style={{flexDirection:"row",backgroundColor:c.surface,borderWidth:1,borderColor:c.borderLight,borderRadius:rad.lg,marginTop:sp.lg,paddingVertical:sp.md,paddingHorizontal:sp.xxl}}><View style={{flex:1,alignItems:"center"}}><Text style={{fontSize:fs.lg,fontWeight:fw.semi,color:c.text}}>{p.followerCount||0}</Text><Text style={{fontSize:fs.xs,color:c.textMuted}}>Followers</Text></View><View style={{width:1,backgroundColor:c.borderLight,marginHorizontal:sp.lg}}/><View style={{flex:1,alignItems:"center"}}><Text style={{fontSize:fs.lg,fontWeight:fw.semi,color:c.text}}>{p.artworkCount||0}</Text><Text style={{fontSize:fs.xs,color:c.textMuted}}>Works</Text></View></View>
<View style={{flexDirection:"row",gap:sp.sm,marginTop:sp.md}}><T style={{backgroundColor:fol?"transparent":c.teal,borderWidth:1.5,borderColor:c.teal,borderRadius:rad.md,paddingVertical:12,paddingHorizontal:32}} onPress={async()=>{try{var r=await users.follow(p._id);sF(r.following)}catch{}}}><Text style={{fontSize:fs.sm,fontWeight:fw.semi,color:fol?c.teal:c.textInverse}}>{fol?"Following":"Follow"}</Text></T><T style={{borderWidth:1.5,borderColor:c.border,borderRadius:rad.md,paddingVertical:12,paddingHorizontal:32}} onPress={()=>n.navigate("Messages",{screen:"Chat",params:{conversationId:null,participantId:p._id,name:p.displayName}})}><Text style={{fontSize:fs.sm,fontWeight:fw.semi,color:c.text}}>Message</Text></T></View>
{arts.length>0&&<Text style={{fontSize:fs.xxs,letterSpacing:2,color:c.textMuted,fontWeight:fw.semi,alignSelf:"flex-start",marginTop:sp.xl}}>WORKS</Text>}</View>} renderItem={({item:i,index:idx})=><T style={{width:CW,marginBottom:sp.md,...(idx%2===0?{marginRight:G/2}:{marginLeft:G/2})}} onPress={()=>n.navigate("ArtworkDetail",{id:i._id})}><Image source={{uri:i.primaryImage}} style={{width:"100%",aspectRatio:0.75,borderRadius:rad.md,backgroundColor:c.surfaceDim}}/><Text style={{fontSize:fs.xs,fontWeight:fw.medium,color:c.text,marginTop:sp.xs}} numberOfLines={1}>{i.title}</Text>{i.pricing?.price>0&&<Text style={{fontSize:fs.xs,color:c.teal,fontWeight:fw.bold,marginTop:2}}>${i.pricing.price.toLocaleString()}</Text>}</T>}/>}
