import{useState}from"react";import{View,Text,TextInput,ScrollView,TouchableOpacity as T,Image,ActivityIndicator,Dimensions}from"react-native";import{search as searchSvc}from"../../services/data";import{colors as c,fs,fw,sp,rad}from"../../constants/theme";
var W=Dimensions.get("window").width;
export default function SearchScreen({navigation:n}){var[q,sQ]=useState("");var[res,sR]=useState(null);var[ld,sL]=useState(false);var[tab,sT]=useState("all");
var go=async()=>{if(q.trim().length<2)return;sL(true);try{sR(await searchSvc.query(q.trim(),tab))}catch{}sL(false)};
return<View style={{flex:1,backgroundColor:c.bg}}><View style={{paddingHorizontal:sp.lg,paddingTop:sp.md}}><TextInput style={{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:rad.md,paddingHorizontal:sp.md,paddingVertical:14,fontSize:fs.md,color:c.text}} value={q} onChangeText={sQ} onSubmitEditing={go} placeholder="Search everything..." placeholderTextColor={c.textMuted} returnKeyType="search" autoFocus/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingHorizontal:sp.lg,gap:sp.sm,paddingVertical:sp.md}}>{["all","artworks","users","events","exhibitions","music"].map(t=><T key={t} style={{paddingHorizontal:14,paddingVertical:8,borderRadius:rad.full,backgroundColor:tab===t?c.teal:c.surface,borderWidth:1,borderColor:tab===t?c.teal:c.border,shadowColor:tab===t?"#000":"transparent",shadowOffset:{width:0,height:2},shadowOpacity:tab===t?0.15:0,shadowRadius:4,elevation:tab===t?3:0}} onPress={()=>{sT(t);if(q.trim().length>=2)setTimeout(go,0)}}><Text style={{fontSize:fs.sm,color:tab===t?c.textInverse:c.textSecondary,fontWeight:fw.medium,textTransform:"capitalize"}}>{t}</Text></T>)}</ScrollView>
{ld?<ActivityIndicator style={{marginTop:40}} color={c.teal}/>:res?<ScrollView contentContainerStyle={{paddingBottom:100}}>
{res.artworks?.length>0&&<Section title="Artworks">{res.artworks.map(i=><T key={i._id} style={{flexDirection:"row",gap:sp.md,paddingHorizontal:sp.lg,paddingVertical:sp.sm}} onPress={()=>n.navigate("Explore",{screen:"ArtworkDetail",params:{id:i._id}})}><Image source={{uri:i.primaryImage}} style={{width:50,height:50,borderRadius:rad.sm,backgroundColor:c.surfaceDim}}/><View style={{flex:1,justifyContent:"center"}}><Text style={{fontSize:fs.md,fontWeight:fw.semi,color:c.text}}>{i.title}</Text><Text style={{fontSize:fs.xs,color:c.textSecondary}}>{i.artistId?.displayName}</Text></View></T>)}</Section>}
{res.users?.length>0&&<Section title="Artists & Users">{res.users.map(i=><T key={i._id} style={{flexDirection:"row",gap:sp.md,paddingHorizontal:sp.lg,paddingVertical:sp.sm}}>{i.avatar?<Image source={{uri:i.avatar}} style={{width:44,height:44,borderRadius:22}}/>:<View style={{width:44,height:44,borderRadius:22,backgroundColor:c.surfaceDim}}/>}<View style={{flex:1,justifyContent:"center"}}><Text style={{fontSize:fs.md,fontWeight:fw.semi,color:c.text}}>{i.displayName}</Text><Text style={{fontSize:fs.xs,color:c.textMuted}}>@{i.username} · {i.role}</Text></View></T>)}</Section>}
{res.events?.length>0&&<Section title="Events">{res.events.map(i=><T key={i._id} style={{paddingHorizontal:sp.lg,paddingVertical:sp.sm}}><Text style={{fontSize:fs.md,fontWeight:fw.medium,color:c.text}}>{i.title}</Text><Text style={{fontSize:fs.xs,color:c.textMuted,marginTop:2}}>{i.type?.replace("_"," ")}</Text></T>)}</Section>}
{res.exhibitions?.length>0&&<Section title="Exhibitions">{res.exhibitions.map(i=><T key={i._id} style={{paddingHorizontal:sp.lg,paddingVertical:sp.sm}}><Text style={{fontSize:fs.md,fontWeight:fw.medium,color:c.text}}>{i.title}</Text></T>)}</Section>}
{res.music?.length>0&&<Section title="Music">{res.music.map(i=><T key={i._id} style={{paddingHorizontal:sp.lg,paddingVertical:sp.sm}}><Text style={{fontSize:fs.md,fontWeight:fw.medium,color:c.text}}>{i.title}</Text><Text style={{fontSize:fs.xs,color:c.textMuted,marginTop:2}}>{i.genre?.join(", ")}</Text></T>)}</Section>}
{Object.values(res).every(a=>!a?.length)&&<Text style={{textAlign:"center",color:c.textMuted,marginTop:40}}>No results found</Text>}
</ScrollView>:<View style={{alignItems:"center",marginTop:60}}><Text style={{fontSize:40,marginBottom:sp.md}}>🔍</Text><Text style={{fontSize:fs.md,color:c.textMuted}}>Search artworks, artists, events...</Text></View>}</View>}
function Section({title,children}){return<View style={{marginBottom:sp.lg}}><Text style={{fontSize:fs.xxs,letterSpacing:2,color:c.textMuted,fontWeight:fw.semi,paddingHorizontal:sp.lg,marginBottom:sp.sm}}>{title.toUpperCase()}</Text>{children}</View>}
