import{useState,useEffect}from"react";import{View,Text,ScrollView,TouchableOpacity as T,TextInput,ActivityIndicator,Alert,Image}from"react-native";import{commissions as comSvc}from"../../services/data";import{useAuth}from"../../store/authStore";import{colors as c,fs,fw,sp,rad}from"../../constants/theme";import{format}from"date-fns";
export default function CommDetail({route}){var{id}=route.params;var[cm,sC]=useState(null);var[ld,sL]=useState(true);var[msg,sM]=useState("");var{user}=useAuth();
useEffect(()=>{(async()=>{try{sC(await comSvc.get(id))}catch{}sL(false)})()},[id]);
var sendMsg=async()=>{if(!msg.trim())return;try{var d=await comSvc.update(id,{message:msg.trim()});sC(d.data||d);sM("")}catch{Alert.alert("Error","Failed to send")}};
var updateStatus=async(s)=>{try{var d=await comSvc.update(id,{status:s});sC(d.data||d)}catch{Alert.alert("Error","Failed")}};
if(ld)return<View style={{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:c.bg}}><ActivityIndicator color={c.teal}/></View>;
if(!cm)return<View style={{flex:1,backgroundColor:c.bg}}><Text style={{color:c.textMuted,textAlign:"center",marginTop:60}}>Not found</Text></View>;
var isArtist=cm.artistId?._id===user?._id;
return<ScrollView style={{flex:1,backgroundColor:c.bg}} contentContainerStyle={{paddingBottom:100}}><View style={{margin:sp.md,backgroundColor:c.surface,borderRadius:rad.lg,padding:sp.lg,borderWidth:1,borderColor:c.borderLight}}><Text style={{fontSize:fs.xxl,fontWeight:fw.light,color:c.text,marginBottom:sp.md}}>{cm.title}</Text><View style={{gap:sp.md}}><Row l="Status" v={cm.status?.replace("_"," ")}/><Row l="Client" v={cm.clientId?.displayName}/><Row l="Artist" v={cm.artistId?.displayName}/>{cm.budget?.min&&<Row l="Budget" v={`$${cm.budget.min} - $${cm.budget.max}`}/>}{cm.timeline&&<Row l="Timeline" v={cm.timeline}/>}</View>{cm.description&&<Text style={{fontSize:fs.md,color:c.textSecondary,lineHeight:24,marginTop:sp.lg}}>{cm.description}</Text>}
{isArtist&&cm.status==="requested"&&<View style={{flexDirection:"row",gap:sp.sm,marginTop:sp.lg}}><T style={{flex:1,backgroundColor:c.tealLight,paddingVertical:14,alignItems:"center",borderRadius:rad.md}} onPress={()=>updateStatus("accepted")}><Text style={{color:c.textInverse,fontWeight:fw.semi}}>Accept</Text></T><T style={{flex:1,borderWidth:1,borderColor:c.error,paddingVertical:14,alignItems:"center",borderRadius:rad.md}} onPress={()=>updateStatus("cancelled")}><Text style={{color:c.error,fontWeight:fw.semi}}>Decline</Text></T></View>}</View>
{cm.messages?.length>0&&<View style={{margin:sp.md,marginTop:0,backgroundColor:c.surface,borderRadius:rad.lg,padding:sp.lg,borderWidth:1,borderColor:c.borderLight}}><Text style={{fontSize:fs.xxs,letterSpacing:2,color:c.textMuted,fontWeight:fw.semi,marginBottom:sp.md}}>MESSAGES</Text>{cm.messages.map((m,i)=><View key={i} style={{paddingVertical:sp.sm,borderBottomWidth:i<cm.messages.length-1?1:0,borderBottomColor:c.borderLight}}><View style={{flexDirection:"row",justifyContent:"space-between"}}><Text style={{fontSize:fs.sm,fontWeight:fw.semi,color:c.text}}>{m.senderId?.displayName||"User"}</Text><Text style={{fontSize:fs.xs,color:c.textMuted}}>{format(new Date(m.timestamp),"MMM d, HH:mm")}</Text></View><Text style={{fontSize:fs.md,color:c.textSecondary,marginTop:sp.xs}}>{m.text}</Text></View>)}</View>}
<View style={{marginHorizontal:sp.md,flexDirection:"row",gap:sp.sm}}><TextInput style={{flex:1,backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:rad.md,paddingHorizontal:sp.md,paddingVertical:12,fontSize:fs.md,color:c.text}} value={msg} onChangeText={sM} placeholder="Add a message..." placeholderTextColor={c.textMuted}/><T style={{backgroundColor:c.teal,borderRadius:rad.md,paddingHorizontal:sp.lg,justifyContent:"center",shadowColor:"#000",shadowOffset:{width:0,height:2},shadowOpacity:0.15,shadowRadius:4,elevation:4}} onPress={sendMsg}><Text style={{color:c.textInverse,fontWeight:fw.semi}}>Send</Text></T></View></ScrollView>}
function Row({l,v}){return<View style={{flexDirection:"row",justifyContent:"space-between"}}><Text style={{fontSize:fs.sm,color:c.textMuted}}>{l}</Text><Text style={{fontSize:fs.sm,color:c.text,textTransform:"capitalize"}}>{v}</Text></View>}
